apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bidnamic-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bidnamic-app.labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end }}